[workspace]
members = [
    "abi",
    "cli",
    "common",
    "function",
    "trigger",
    "service",
    "wasm",
    "examples/wasm/hello-world-lib",
    "examples/wasm/rust-event-handler",
    "examples/wasm/rust-event-handler-lib",
]
