name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-rust:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: '5.0'
          mongodb-username: test
          mongodb-password: test
          mongodb-db: trigger_unittest
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Install Rust
        run: rustup toolchain install stable --component llvm-tools-preview
      - name: Install wasm32-wasi target
        run: rustup target add wasm32-wasi
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: install nextest
        uses: taiki-e/install-action@nextest
      - uses: Swatinem/rust-cache@v1
      - name: Check code format
        run: cargo fmt -- --check
      - name: Check the package for errors
        run: cargo check --all
      - name: Lint rust sources
        run: cargo clippy --all-targets --all-features --tests --benches -- -D warnings
      - name: build wasm lib examples
        run: cargo build --release --target wasm32-wasi -p example-wasm-hello-world-lib -p example-wasm-rust-event-handler-lib -p example-wasm-rust-event-handler
      - name: Execute rust tests
        run: cargo nextest run --all-features
